# Generated by Django 6.1 on 2026-09-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_currency_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('PKR', 'Pakistani Rupee')], default='PKR', editable=False, max_length=3),
        ),
    ]
