# Generated by Django 6.1 on 2026-09-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card'), ('online', 'Online')], max_length=30),
        ),
    ]
