# Generated by Django 6.1 on 2026-09-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Card Payment')], max_length=30),
        ),
    ]
